### ISSUE TITLE
Handle transitive dependencies

### ISSUE THREAD

**Issue by JD557** [indoorvivants/sn-vcpkg#153]
When running something like `sn-vcpkg scala-cli libidn2`, vcpkg fetchs the libraries and it's [dependencies](https://github.com/microsoft/vcpkg/blob/master/ports/libidn2/vcpkg.json#L8-L11)

However, it appears that those are not automatically injected in the `--native-compile/--native-linking`, so one always needs to specify all transitive dependencies manually.

It would be nice if those were automatically included, which doesn't seem to be the case now.

**Comment by keynmol** [comment]
Hm, generally this depends on the quality of pkg-config file that gets installed. Some of them do mention the dependencies, and therefore pkg-config itself collects all the args.

In this case it seems that I get the transitive flags:

```
> cs launch sn-vcpkg:0.0.18 --contrib -- scala-cli libidn2 -v -- --help 2>&1 | grep "Invoking Scala CLI"
    Invoking Scala CLI with arguments: [scala-cli --help --native-compile -I/Users/velvetbaldmime/Library/Caches/sbt-vcpkg/vcpkg-install/arm64-osx/lib/pkgconfig/../../include --native-linking -L/Users/antonsviridov/Library/Caches/sbt-vcpkg/vcpkg-install/arm64-osx/lib/pkgconfig/../../lib --native-linking -lidn2 --native-linking -liconv --native-linking -lunistring]
```

This is on a Mac. Are you getting a different result on windows?

**Comment by JD557** [comment]
On windows I got:

```
[error]     Invoking Scala CLI with arguments: [scala-cli.bat --help --native-compile -IC:\roothome\vcpkg\packages\libidn2_x64-windows-static\include --native-linking -LC:\roothome\vcpkg\packages\libidn2_x64-windows-static\lib --native-linking C:\roothome\vcpkg\packages\libidn2_x64-windows-static\lib\idn2.lib]
```

So no mentions of `iconv` or `unistring` 🤔 

(with `scala-cli --vcpkg-root-manual C:\\roothome\\vcpkg --vcpkg-install C:\\roothome\\vcpkg libidn2 -v -- --help`)

**Comment by keynmol** [comment]
So under the `vcpkg-install` location (which probably should be separate from your vcpkg-root) you should have `<triplet>/lib/pkgconfig/` or something folder. 

Can you find a .pc file corresponding to libidn2 there?

Also, those arguments look approximated.. does the CLI say anything about that?

**Comment by JD557** [comment]
> Can you find a .pc file corresponding to libidn2 there?

```
PS C:\roothome\vcpkg\x64-windows-static\lib\pkgconfig> cat .\libidn2.pc
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${prefix}/lib

Name: libidn2
Description: Library implementing IDNA2008 and TR46
Version: 2.3.4

Libs: "-L${libdir}" -lidn2 -liconv -lunistring -liconv
Cflags: "-I${includedir}"
```

> Also, those arguments look approximated.. does the CLI say anything about that?

Yes!

[error]     Compilation flags for `libidn2` dependency were approximate, and might be incorrect. If you want to disable approximation, set `vcpkgNativeApprxomate := false`
[error]     Linking flags for `libidn2` dependency were approximated, and might be incorrect. If you want to disable approximation, set `vcpkgNativeApprxomate := false`

**Comment by keynmol** [comment]
Right, so this seems to be less about sn-vcpkg doing the wrong thing with transitive dependencies (which is handled by pkg-config), but perhaps it's not finding the `.pc` file correctly on windows.

I'll try and reproduce it on CI

**Comment by JD557** [comment]
I wonder if it's something related to my setup, then (notice the `--vcpkg-root-manual C:\\roothome\\vcpkg --vcpkg-install C:\\roothome\\vcpkg`, as I can't use the defaults).

**Comment by keynmol** [comment]
Why can't you use the defaults btw? May be I've made some assumptions I shouldn't have.

Tbh this separation of root and install was an early idea of mine before I knew much about vcpkg, wanting to retain control over the binary artifacts and headers, as opposed to relying on Github Actions managing those (vcpkg is available in some form on all platforms I think, with locations configured via VCPKG_* env variables presets) - just to make sure caches could be created independently.

I can't say whether it's the right way of using vcpkg, but it has proved fruitful on CI.

**Comment by JD557** [comment]
My home directory is `C:\Users\João\`, and vcpkg doesn't seem to like non ASCII paths very much.

**Comment by JD557** [comment]
OK, I figured out the issue, I needed to install pkgconfig (`choco install pkgconfiglite`).

Closing this issue.
